title: Abid Ahmed S
description:
  <p align="center">
  <a href="pdf/abidprofile-latest.pdf"><font color="red">Resume</a> |
  <a href="https://www.linkedin.com/abidahmed/"><font color="red">LinkedIn</a>
  <font color="black">
  
  <br>   
  Technical evangelist who has interests in developing ML models for real time Telco 5G SW.
  Satrting to work on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  working in Ericsson India in telecom domain for last 6 years with overall 22+ years experience.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
